spring.application.name=jobportal

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/jobportal
spring.datasource.username=postgres
spring.datasource.password=postgres123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Cloudinary
cloudinary.cloud-name=dlr0c2hlr
cloudinary.api-key=165572483258856
cloudinary.api-secret=_3F1xlkuSsf1uZd_QhIkZqKSur0

logging.level.com.jobportal=DEBUG